#!/usr/bin/env npx tsx
/**
 * Resolve semantic director cues to frame-accurate renderer cues.
 *
 * The semantic draft is never consumed directly by production renderers. When
 * audio/subtitle anchors are stale or unresolved, this script writes a blocked
 * resolution report and generates an empty runtime cue map.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { buildDirectorCueResolution } from "../utils/directorCueResolution";
import type { DirectorCueResolution } from "../utils/directorCueResolution";

const ROOT = path.resolve(__dirname, "../../..");
const DATA_DIR = path.join(ROOT, "src/video-system/data");

const DIRECTOR_CUES_DRAFT_PATH = path.join(DATA_DIR, "directorCuesDraft.json");
const VIDEO_SPEC_PATH = path.join(DATA_DIR, "videoSpec.json");
const AUDIO_TIMING_PATH = path.join(DATA_DIR, "audioTiming.json");
const SUBTITLES_PATH = path.join(DATA_DIR, "subtitles.json");
const OUTPUT_PATH = path.join(DATA_DIR, "directorCuesResolved.json");
const RUNTIME_OUTPUT_PATH = path.join(DATA_DIR, "directorCuesRuntime.ts");
const FPS = 30;
const DEFAULT_DECAY_FRAMES = 15;

function readJson<T>(filePath: string): T {
  return JSON.parse(fs.readFileSync(filePath, "utf-8")) as T;
}

function quote(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function buildRuntimeSource(resolution: DirectorCueResolution): string {
  const runtime: Record<
    string,
    {
      mode: "strict-switch" | "progressive-retain";
      leadFrames: number;
      decayFrames: number;
      cues: Array<{
        cueId: string;
        target: string;
        startFrameEstimate: number;
        leadFrames: number;
        holdFrames?: number;
        support: "audio-aligned";
      }>;
    }
  > = {};

  if (resolution.summary.rendererConsumable) {
    for (const scene of resolution.scenes) {
      const mode =
        scene.mode === "progressive-retain"
          ? "progressive-retain"
          : "strict-switch";
      const resolvedCues = scene.cues.filter(
        (cue) =>
          cue.timingStatus === "resolved" && cue.startFrame !== null,
      );
      if (resolvedCues.length === 0) continue;

      runtime[scene.sceneId] = {
        mode,
        leadFrames: 0,
        decayFrames: DEFAULT_DECAY_FRAMES,
        cues: resolvedCues.map((cue) => ({
          cueId: cue.cueId,
          target: cue.activeTarget,
          startFrameEstimate: cue.startFrame as number,
          leadFrames: 0,
          ...(cue.endFrame !== null && cue.startFrame !== null
            ? { holdFrames: Math.max(1, cue.endFrame - cue.startFrame) }
            : {}),
          support: "audio-aligned" as const,
        })),
      };
    }
  }

  const generatedAt = new Date().toISOString();
  const reason = resolution.summary.rendererConsumable
    ? "Frame-accurate cues generated from the active audio and subtitles."
    : resolution.summary.blockingReason ??
      "Resolved cues are not safe for renderer consumption.";

  return `/**\n * AUTO-GENERATED by src/video-system/scripts/resolve-director-cues.ts.\n * Do not hand-edit. Semantic drafts live in directorCuesDraft.json.\n */\n\nexport interface DirectorCue {\n  cueId: string;\n  target: string;\n  startFrameEstimate: number;\n  leadFrames?: number;\n  holdFrames?: number;\n  support?: \"audio-aligned\" | \"resolved\" | \"reference-only\";\n  motionIntent?: string;\n}\n\nexport interface SceneDirectorCues {\n  mode: \"strict-switch\" | \"progressive-retain\";\n  leadFrames: number;\n  decayFrames: number;\n  cues: DirectorCue[];\n}\n\nexport interface DirectorCuesRuntimeMeta {\n  source: string;\n  status: string;\n  rendererConsumable: boolean;\n  generatedAt: string | null;\n  reason?: string;\n}\n\nexport const directorCuesRuntimeMeta: DirectorCuesRuntimeMeta = ${quote(
    {
      source: "src/video-system/data/directorCuesResolved.json",
      status: resolution.status,
      rendererConsumable: resolution.summary.rendererConsumable,
      generatedAt,
      reason,
    },
  )};\n\nexport const directorCuesRuntime: Record<string, SceneDirectorCues> = ${quote(
    runtime,
  )};\n`;
}

function main() {
  const resolution = buildDirectorCueResolution({
    fps: FPS,
    draft: readJson(DIRECTOR_CUES_DRAFT_PATH),
    videoSpec: readJson(VIDEO_SPEC_PATH),
    audioTiming: readJson(AUDIO_TIMING_PATH),
    subtitles: readJson(SUBTITLES_PATH),
  });

  fs.writeFileSync(OUTPUT_PATH, `${JSON.stringify(resolution, null, 2)}\n`);
  fs.writeFileSync(RUNTIME_OUTPUT_PATH, buildRuntimeSource(resolution));

  console.log(`directorCuesResolved: ${OUTPUT_PATH}`);
  console.log(`directorCuesRuntime: ${RUNTIME_OUTPUT_PATH}`);
  console.log(`status: ${resolution.status}`);
  console.log(`rendererConsumable: ${resolution.summary.rendererConsumable}`);
  console.log(`resolvedCueCount: ${resolution.summary.resolvedCueCount}`);
  console.log(`unresolvedCueCount: ${resolution.summary.unresolvedCueCount}`);

  if (!resolution.summary.rendererConsumable) {
    console.log("visualGateStatus: inspect");
    console.log("runtimeCueMap: empty (safe fallback)");
  }
}

main();
